#!/usr/bin/with-contenv bash

# Load rc config for openbox
if [[ ! -f /config/.config/openbox/rc.xml ]]; then
  mkdir -p /config/.config/openbox && \
  cp /defaults/rc.xml /config/.config/openbox/rc.xml && \
  chown -R abc:abc /config/.config/openbox/rc.xml
fi
